services:
  - type: web
    name: bazarchic-db-tool
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DB_HOST
        value: pp-lb.bazarchic.com
      - key: DB_USER
        value: bazar
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: bazarshop_base
      - key: DB_PORT
        value: 3306
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: DROPBOX_TOKEN
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
